set nocompatible              " be iMproved, required
filetype off                  " required

let g:netrw_dirhistmax = 0

let $MYVIMDIR=expand("<sfile>:h")
source $MYVIMDIR/xdg.vim

set rtp+=$MYVIMDIR/bundle/Vundle.vim
call vundle#begin("~/.config/vim/bundle")
Plugin 'gmarik/Vundle.vim'
Plugin 'rust-lang/rust.vim'
Plugin 'neoclide/coc.nvim'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'CraigGiles/scala.vim'
call vundle#end()            " required
filetype plugin indent on    " required

syntax on
set number
set mouse=r

set viewdir=$MYVIMDIR/view

let g:rustfmt_autosave = 1

source $MYVIMDIR/xdg.vim
autocmd FileType sql :setlocal sw=2 ts=2 sts=2

nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
nmap <leader>qf  :<C-u>CocFix<cr>
nnoremap <silent><nowait> <space>s  :<C-u>CocList -I symbols<cr>

set scl=no

let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
set hidden
nmap <leader>bb :CtrlPBuffer<cr>

highlight CocErrorFloat ctermbg=Red ctermfg=Black
highlight CocFloating ctermbg=Red ctermfg=Black
let g:netrw_liststyle = 3
let g:netrw_banner = 0
