" Hack for CtrlP compat with foot terminal
set term=rxvt-256color
set nocompatible              " be iMproved, required
filetype off                  " required

let g:netrw_dirhistmax = 0

let $MYVIMDIR=expand("<sfile>:h")
source $MYVIMDIR/xdg.vim

set rtp+=$MYVIMDIR/bundle/Vundle.vim
call vundle#begin("~/.config/vim/bundle")
Plugin 'gmarik/Vundle.vim'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'prabirshrestha/vim-lsp'
Plugin 'mattn/vim-lsp-settings'
Plugin 'arcticicestudio/nord-vim'
call vundle#end()            " required
filetype plugin indent on    " required

syntax on
set number
set mouse=r

set viewdir=$MYVIMDIR/view

let g:rustfmt_autosave = 1

source $MYVIMDIR/xdg.vim
autocmd FileType sql :setlocal sw=2 ts=2 sts=2

nmap <silent> gd <Plug>(lsp-definition)
nmap <silent> gy <Plug>(lsp-type-definition)
nmap <silent> gi <Plug>(lsp-implementation)
nmap <silent> gr <Plug>(lsp-references)
nmap <leader>qf  :<C-u>LspCodeAction<cr>
nmap <buffer> gs <plug>(lsp-workspace-symbol-search)
let g:lsp_format_sync_timeout = 1000
autocmd! BufWritePre *.rs,*.scala call execute('LspDocumentFormatSync')

set scl=no

let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
set hidden
nmap <leader>bb :CtrlPBuffer<cr>

colorscheme nord
autocmd filetype mail set textwidth=0
