let g:molokai_original = 1
set nocompatible
set t_Co=256
colorscheme molokai
syntax on
set number
set nobackup
set nowritebackup
set noundofile

augroup WrapLineInTeXFile
    autocmd!
    autocmd FileType tex setlocal tw=80
augroup END
