set nocompatible              " be iMproved, required
filetype off                  " required

let g:netrw_dirhistmax = 0

let $MYVIMDIR=expand("<sfile>:h")
source $MYVIMDIR/xdg.vim

set rtp+=$MYVIMDIR/bundle/Vundle.vim
call vundle#begin("~/.config/vim/bundle")
Plugin 'gmarik/Vundle.vim'
Plugin 'rust-lang/rust.vim'
call vundle#end()            " required
filetype plugin indent on    " required

syntax on
set number
set nobackup
set nowritebackup
set noundofile
set mouse=r

set viewdir=$MYVIMDIR/view

colorscheme delek
let g:rustfmt_autosave = 1
let g:ycm_rust_src_path = '/home/simon/.multirust/src'

source $MYVIMDIR/xdg.vim
autocmd FileType sql :setlocal sw=2 ts=2 sts=2
