#!/bin/bash

set -euo pipefail

DB_PATH="/tmp/albumqueue.db"

function flaql() {
	INIT_SQL=".load /usr/local/lib/libflaql
		  create virtual table if not exists flacs using flac(\"/home/simon/media/imported\");"
	sqlite3 -init <(echo "$INIT_SQL") "$DB_PATH" "$1"
}

IFS='	'
mpc clear

flaql "select
	max(case when lower(tag) = 'albumartist' then value end) || ' - ' ||
		max(case when lower(tag) = 'album' then value end) || '	' || path
       from flacs group by path" 2>/dev/null \
  | while read album f; do
	 dir=$(dirname "$f")
	 echo "$album	$dir"
    done | uniq | dmenu -t | cut -f2 | cut -d/ -f5- | xargs -I % mpc add "%"
