#!/bin/bash

MEDIA_DIR=~/media
RATING=$1

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 RATING" >&2
	exit 1
fi

mpc playlist -f '%file%' | xargs -d '\n' -I % metaflac --set-tag=RATING=$RATING "$MEDIA_DIR/%"
