#!/bin/bash
WITH_EMAIL=true
WITH_BATTERY=false
STATUS=""

if [ "$WITH_EMAIL" = true ]; then
	EMAIL_ICON=""
	EMAIL_CREDENTIALS=`cat ~/.config/emailcredentials`
	EMAILS=`curl \
		--url imaps://imap.mailbox.org/INBOX \
		--user "$EMAIL_CREDENTIALS" \
		-X 'EXAMINE INBOX' 2>&1 \
		| grep -oP '\* \K[0-9]*(?= EXIST)'`
	if [[ "$EMAILS" != 0 && "$EMAILS" != "" ]]; then
		EMAIL_LINE=$(echo -e "\x04 $EMAIL_ICON $EMAILS \x01 ")
		STATUS="$STATUS$EMAIL_LINE"
	fi
fi

if [ "$WITH_BATTERY" = true ]; then
	battery=$(acpi -b | cut -d"," -f2 | cut -d" " -f2 | cut -d'%' -f1)
	if [ $battery -lt "15" ]; then
		STATUS="$STATUS$(echo -e "\x03 ")"
	else
		STATUS="$STATUS$(echo -e "\x02 ")"
	fi
	STATUS="$STATUS$battery%"
fi

STATUS="$STATUS $(date +"%H:%M")"
xsetroot -name "$STATUS"
