#!/bin/sh

export MOZ_ENABLE_WAYLAND=1

mod="Mod1"

# Mod+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal $mod+Shift Return spawn foot

riverctl map normal $mod b spawn firefox-wayland
riverctl map normal $mod m spawn 'dmenu-wl_run -nb "#000000" -nf "#FFFFFF" -sf "#000000" -sb "#FFFFFF" -h 24 -m 1 -fn "mono 11" | grep -s "No monitor" || dmenu-wl_run -nb "#000000" -nf "#FFFFFF" -sf "#000000" -sb "#FFFFFF" -h 24 -m 0 -fn "mono 11"'

# Mod+Q to close the focused view
riverctl map normal $mod+Shift x close

# Mod+Shift+E to exit river
riverctl map normal $mod+Shift E exit

# Mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod Tab focus-view next
riverctl map normal $mod+Shift Tab focus-view previous

# Mod+Return to bump the focused view to the top of the layout stack
riverctl map normal $mod Return zoom

# Mod+H and Mod+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

for i in $(seq 1 4)
do
    tags=$((1 << ($i - 1)))

    # Mod+[1-9] to focus tag [0-8]
    riverctl map normal $mod+Control $i set-focused-tags $tags

    # Mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $mod+Shift $i set-view-tags $tags

    # Mod+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $mod $i toggle-focused-tags $tags
done

riverctl map normal $mod Comma send-to-output next

# Mod+Space to toggle float
riverctl map normal $mod Space toggle-float

# Mod+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# Drag windows with mouse when alt is pressed
riverctl map-pointer normal Mod1 BTN_LEFT move-view
riverctl map-pointer normal Mod1 BTN_RIGHT resize-view

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add title "popup title with spaces"

# Set app-ids and titles of views which should use client side decorations
riverctl csd-filter-add app-id "gedit"

swaybg -m tile -i ~/.local/share/wall.png &

riverctl border-width 5
riverctl border-color-focused 0x81A1C1
riverctl border-color-unfocused 0x4C566A

riverctl focus-follows-cursor normal

riverctl focus-output next

prowler &

riverctl map normal $mod escape spawn 'davis toggle'

riverctl map normal None XF86MonBrightnessDown spawn 'xbacklight -dec 10'
riverctl map normal None XF86MonBrightnessUp spawn 'xbacklight -inc 10'

riverctl map normal $mod+Shift l spawn swaylock

riverctl spawn dunst
riverctl spawn 'levee battery'
riverctl spawn 'wlr-randr --output HDMI-A-1 --pos 0,0 --output eDP-1 --pos 3840,1080'

dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river

# Set and exec into the default layout generator, rivertile.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
exec rivertile -view-padding 10 -outer-padding 10
